package io.openliberty.tools.gradle

import org.junit.AfterClass
import org.junit.BeforeClass
import org.junit.Test

import java.io.BufferedReader
import java.io.FileReader
import java.util.ArrayList


import org.junit.BeforeClass
import org.junit.FixMethodOrder
import org.junit.Test
import org.junit.runners.MethodSorters
import org.junit.Assert;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
class TestAppendServerEnvWithProps extends AbstractIntegrationTest {
    static File resourceDir = new File("build/resources/test/sample.servlet")
    static File buildDir = new File(integTestDir, "/test-append-server-env-with-props")
    static String buildFilename = "testAppendServerEnvWithEnvProps.gradle"

    @BeforeClass
    public static void setup() {
        createDir(buildDir)
        createTestProject(buildDir, resourceDir, buildFilename)
        runTasks(buildDir, 'libertyCreate')
    }

    @Test
    public void check_for_server_env() {
        assert new File('build/testBuilds/test-append-server-env-with-props/build/wlp/usr/servers/LibertyProjectServer/server.env').exists() : 'server.env not found!'
    }

    /*
        # envProps in build.gradle
        env = ['TEST_PROP_2':'white', 'CONFIG_SERVER_ENV_PROPS':'TEST']
        
        # default server.env
        keystore_password=sfKRrA1ioLdtIFQC9bEfkua

        # Configured server.env
        CONFIG_SERVER_ENV=TEST
        TEST_PROP_2=green
        TEST_PROP_3=blue

        # server.env in configDir
        ConfigDir=TEST
        TEST_PROP_1=red
        TEST_PROP_2=red
        TEST_PROP_3=red

        # Merged server.env
        # Generated by liberty-gradle-plugin
        keystore_password=sfKRrA1ioLdtIFQC9bEfkua
        CONFIG_SERVER_ENV=TEST
        ConfigDir=TEST
        TEST_PROP_3=blue
        CONFIG_SERVER_ENV_PROPS=TEST
        TEST_PROP_2=white
        TEST_PROP_1=red
    */
    @Test
    public void check_server_env_contents() {
        File serverEnv = new File("build/testBuilds/test-append-server-env-with-props/build/wlp/usr/servers/LibertyProjectServer/server.env")

        Map<String,String> serverEnvContents = new HashMap<String,String>()
        BufferedReader bf = new BufferedReader(new FileReader(serverEnv))
        String line = bf.readLine()
        boolean commentFound = false
        while(line != null) {
            if(!line.startsWith("#")) {
                String[] keyValuePair = line.split("=", 2)
                serverEnvContents.put(keyValuePair[0], keyValuePair[1])
            } else {
                commentFound = true
                Assert.assertTrue("File should have been generated by liberty-gradle-plugin", line.contains("liberty-gradle-plugin"))
            }
            line = bf.readLine()
        }
        Assert.assertTrue("Expected generated by liberty-gradle-plugin comment not found", commentFound)

        Assert.assertTrue("Number of env properties should be >= 11, but is "+serverEnvContents.size(), serverEnvContents.size() >= 11)
        Assert.assertTrue("keystore_password mapping found", serverEnvContents.containsKey("keystore_password"))
        Assert.assertTrue("ConfigDir=TEST mapping found", serverEnvContents.get("ConfigDir").equals("TEST"))
        Assert.assertTrue("CONFIG_SERVER_ENV=TEST mapping found", serverEnvContents.get("CONFIG_SERVER_ENV").equals("TEST"))
        Assert.assertTrue("TEST_PROP_3=blue", serverEnvContents.get("TEST_PROP_3").equals("blue"))
        Assert.assertTrue("CONFIG_SERVER_ENV_PROPS=TEST", serverEnvContents.get("CONFIG_SERVER_ENV_PROPS").equals("TEST"))
        Assert.assertTrue("TEST_PROP_2=white", serverEnvContents.get("TEST_PROP_2").equals("white"))
        Assert.assertTrue("TEST_PROP_1=red", serverEnvContents.get("TEST_PROP_1").equals("red"))
        // convertServerEnvPathSeparator=true: backslashes must be converted to forward-slashes.
        Assert.assertTrue("WIN_HOME: backslash converted", serverEnvContents.get("WIN_HOME").equals("C:/myfolder/folder2"))
        Assert.assertTrue("WIN_JAVA_HOME: backslash converted", serverEnvContents.get("WIN_JAVA_HOME").equals("!WIN_HOME!/java"))
        Assert.assertTrue("TEST_BACKSLASH_VALUE: backslash converted", serverEnvContents.get("TEST_BACKSLASH_VALUE").equals("abc/`;xyz"))
    }

}