package io.openliberty.tools.gradle

import org.junit.AfterClass
import org.junit.BeforeClass
import org.junit.Test
import org.junit.Assert
import org.junit.FixMethodOrder
import org.junit.runners.MethodSorters

import java.io.BufferedReader
import java.io.FileReader

/**
 * Verifies that when convertServerEnvPathSeparator is not set (defaults to false),
 * backslash characters in server.env values are preserved verbatim in the merged output.
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
class TestAppendServerEnvVerbatim extends AbstractIntegrationTest {
    static File resourceDir = new File("build/resources/test/sample.servlet")
    static File buildDir = new File(integTestDir, "/test-append-server-env-verbatim")
    static String buildFilename = "testAppendServerEnvVerbatim.gradle"

    @BeforeClass
    public static void setup() {
        createDir(buildDir)
        createTestProject(buildDir, resourceDir, buildFilename)
        runTasks(buildDir, 'libertyCreate')
    }

    @Test
    public void check_for_server_env() {
        assert new File('build/testBuilds/test-append-server-env-verbatim/build/wlp/usr/servers/LibertyProjectServer/server.env').exists() : 'server.env not found!'
    }

    /*
        # convertServerEnvPathSeparator defaults to false — verbatim mode.
        # All backslash characters must survive unchanged in the merged server.env.
        #
        # server.env entries with backslashes (src/resources/server.env):
        #   WIN_HOME=C:\myfolder\folder2
        #   WIN_JAVA_HOME=!WIN_HOME!\java
        #   TEST_BACKSLASH_VALUE=abc\`;xyz
        #
        # env map entry:
        #   GRADLE_WIN_PATH=C:\Semeru\jdk
    */
    @Test
    public void check_server_env_contents() {
        File serverEnv = new File("build/testBuilds/test-append-server-env-verbatim/build/wlp/usr/servers/LibertyProjectServer/server.env")

        Map<String,String> serverEnvContents = new HashMap<String,String>()
        BufferedReader bf = new BufferedReader(new FileReader(serverEnv))
        String line = bf.readLine()
        boolean commentFound = false
        while (line != null) {
            if (!line.startsWith("#")) {
                String[] kv = line.split("=", 2)
                if (kv.length == 2) {
                    serverEnvContents.put(kv[0], kv[1])
                }
            } else {
                commentFound = true
                Assert.assertTrue("File should have been generated by liberty-gradle-plugin", line.contains("liberty-gradle-plugin"))
            }
            line = bf.readLine()
        }
        Assert.assertTrue("Expected generated by liberty-gradle-plugin comment not found", commentFound)

        Assert.assertTrue("Number of env properties should be >= 12, but is " + serverEnvContents.size(), serverEnvContents.size() >= 12)
        Assert.assertTrue("keystore_password mapping found", serverEnvContents.containsKey("keystore_password"))
        Assert.assertTrue("ConfigDir=TEST", serverEnvContents.get("ConfigDir").equals("TEST"))
        Assert.assertTrue("CONFIG_SERVER_ENV=TEST", serverEnvContents.get("CONFIG_SERVER_ENV").equals("TEST"))
        Assert.assertTrue("TEST_PROP_3=blue", serverEnvContents.get("TEST_PROP_3").equals("blue"))
        Assert.assertTrue("CONFIG_SERVER_ENV_PROPS=TEST", serverEnvContents.get("CONFIG_SERVER_ENV_PROPS").equals("TEST"))
        Assert.assertTrue("TEST_PROP_2=white", serverEnvContents.get("TEST_PROP_2").equals("white"))
        Assert.assertTrue("TEST_PROP_1=red", serverEnvContents.get("TEST_PROP_1").equals("red"))
        // verbatim: backslashes must NOT be converted
        Assert.assertTrue("WIN_HOME: backslash preserved verbatim",
                serverEnvContents.get("WIN_HOME").equals("C:\\myfolder\\folder2"))
        Assert.assertTrue("WIN_JAVA_HOME: expansion variable and backslash preserved verbatim",
                serverEnvContents.get("WIN_JAVA_HOME").equals("!WIN_HOME!\\java"))
        Assert.assertTrue("TEST_BACKSLASH_VALUE: backslash preserved verbatim",
                serverEnvContents.get("TEST_BACKSLASH_VALUE").equals("abc\\`;xyz"))
        Assert.assertTrue("GRADLE_WIN_PATH: inline env value backslash preserved verbatim",
                serverEnvContents.get("GRADLE_WIN_PATH").equals("C:\\Semeru\\jdk"))
    }

    @Test
    public void check_windows_path_and_expansion_variables_preserved() {
        File serverEnv = new File("build/testBuilds/test-append-server-env-verbatim/build/wlp/usr/servers/LibertyProjectServer/server.env")
        List<String> lines = serverEnv.readLines()

        boolean winHomeOk = lines.any { it == "WIN_HOME=C:\\myfolder\\folder2" }
        boolean winJavaHomeOk = lines.any { it == "WIN_JAVA_HOME=!WIN_HOME!\\java" }
        Assert.assertTrue("WIN_HOME line must be verbatim 'WIN_HOME=C:\\myfolder\\folder2'", winHomeOk)
        Assert.assertTrue("WIN_JAVA_HOME line must be verbatim 'WIN_JAVA_HOME=!WIN_HOME!\\java'", winJavaHomeOk)
    }

    @Test
    public void check_expansion_variable_order_preserved() {
        File serverEnv = new File("build/testBuilds/test-append-server-env-verbatim/build/wlp/usr/servers/LibertyProjectServer/server.env")
        List<String> lines = serverEnv.readLines().findAll { !it.startsWith("#") && !it.trim().isEmpty() }

        int winHomeIdx     = lines.findIndexOf { it.startsWith("WIN_HOME=") }
        int winJavaHomeIdx = lines.findIndexOf { it.startsWith("WIN_JAVA_HOME=") }
        Assert.assertTrue("WIN_HOME (idx=$winHomeIdx) must appear before WIN_JAVA_HOME (idx=$winJavaHomeIdx)",
                winHomeIdx >= 0 && winJavaHomeIdx > winHomeIdx)
    }
}
