# Start with OL runtime.
FROM icr.io/appcafe/open-liberty:full-java11-openj9-ubi

ARG VERSION=1.0
ARG REVISION=SNAPSHOT

LABEL \
  org.opencontainers.image.authors="Your Name" \
  org.opencontainers.image.vendor="IBM" \
  org.opencontainers.image.url="local" \
  org.opencontainers.image.version="$VERSION" \
  org.opencontainers.image.revision="$REVISION" \
  vendor="Open Liberty" \
  name="devc-multimodule" \
  version="$VERSION-$REVISION" \
  summary="devc multi-module container test"

USER root

COPY --chown=1001:0 src/main/liberty/config/server.xml /config/

COPY --chown=1001:0 build/libs/*.ear /config/apps/

USER 1001
